<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0-windows;net9.0-windows;netcoreapp3.1;net6.0-windows;net8.0-windows;net462</TargetFrameworks>
		<UseWPF>true</UseWPF>
		<RootNamespace>OpenTK.Wpf</RootNamespace>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>9.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<!--<OutputPath>bin\$(Configuration)\$(TargetFramework)</OutputPath>-->

		<Description>A native control for WPF in OpenTK 3.x and 4.x.. (A Fork of OpenTK to migrate it to .NET10.0 (custom build) and fix dependency issues)</Description>
		<Copyright>Copyright (c) 2025 Team OpenTK</Copyright>
		<Company>Team OpenTK</Company>
		<PackageProjectUrl>https://github.com/ezhassen/GLWpfControl</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ezhassen/GLWpfControl</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageTags>OpenTK, GLWpfControl</PackageTags>
		<PackageId>OpenTKEzz.GLWpfControl</PackageId>
		<Version>4.3.5</Version>
	</PropertyGroup>

	<Choose>
		<When Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
			<ItemGroup>
				<PackageReference Include="OpenTK" Version="4.8.2" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<PackageReference Include="OpenTKEzz.Graphics" Version="4.9.11" />
				<PackageReference Include="OpenTKEzz.Windowing.Desktop" Version="4.9.11" />
			</ItemGroup>
		</Otherwise>
	</Choose>

</Project>
