<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net10.0-windows;netcoreapp3.1;net462</TargetFrameworks>
		<UseWPF>true</UseWPF>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<StartupObject>Example.App</StartupObject>

	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GLWpfControl\GLWpfControl.csproj" />
	</ItemGroup>
</Project>
